;============================================================================
; BATTLE.INI (English)
;
; This control file specifies the battle campaigns that
; are in the game. Additional files that begin with "BATTLE"
; will augment this list.
;
; $Author: Westwood Studios /CO2
; $Archive: $
; $Modtime: 10. 30. 2025$
; $Revision:$
;============================================================================

; ******* Battle List *******
; Lists the various battles in this control file. Each
; battle is given a unique (internal only) identifier name.
[Battles]
0=RACMPGNS
1=scg01ea
2=scg02ea
3=scg03ea
4=scg05ea
5=scg04ea
6=scg06ea
7=scg07ea
8=scg08ea
9=scg09ea
10=scg10ea
11=scg11ea
12=scg12ea
13=scg13ea
14=scg14ea

; ******* Individual Campaign Data *******
; Each battle campaign lists its information
; in a section that cooresponds to its 
; identifier battle name (see above).

[RACMPGNS]
Description=- Red Alert 1 Campaigns -

[scg01ea]
Scenario=Maps\Missions\scg01ea.mpr
NextScenario=Maps\Missions\scg02ea.mpr
UnlockMissions=scg02ea.mpr
Description=  In the thick of it
LongDescription= Rescue Einstein from the Headquarters inside this Soviet complex.  Once found, evacuate him via the helicopter at the signal flare.  Einstein and Tanya must be kept alive at all costs.  Beware the Soviet's Tesla Coils.Direct Tanya to destroy the westmost power plants to take them off-line.
Side=1
SideName=Greece

[scg02ea]
Scenario=Maps\Missions\scg02ea.mpr
RequiresUnlocking=yes
Description=  Five to one
LongDescription= A critical supply convoy is due through this area in 25 minutes, but Soviet forces have blocked the road in several places. Unless you can clear them out, those supplies will never make it to the front. The convoy will come from the northwest, and time is short so work quickly.
Side=1
SideName=Greece

[scg03ea]
CD=-1
Scenario=Maps\Missions\scg03ea.ini
Description=   Dead End
LongDescription= LANDCOM 16 HQS.@TOP SECRET.@TO: FIELD COMMANDER A9@@INTELLIGENCE RECON SHOWS HEAVY SOVIET MOVEMENT IN YOUR AREA. NEARBY BRIDGES ARE KEY TO SOVIET ADVANCEMENT. DESTROY ALL BRIDGES ASAP. TANYA WILL ASSIST. KEEP HER ALIVE AT ALL COSTS.@@CONFIRMATION CODE 1612.@@TRANSMISSION ENDS.
Side=1
SideName=Greece

[scg04ea]
CD=-1
Scenario=Maps\Missions\scg04ea.ini
Description=  Ten to one
LongDescription= Soviet forces are trying to retake the pass you cleared for our convoys. Don't let this happen. Hold the pass and prevent the Soviets from  taking this vital area. Destroy all Soviet units and buildings in this region.
SideName=Greece

[scg05ea]
CD=-1
Scenario=Maps\Missions\scg05ea.ini
Description=  Tanya's Tale
LongDescription= Rescue Tanya. Your spy can move past any enemy unit, except dogs, without being detected. Direct him into the weapons factory located at a nearby Soviet Base where he will hijack a truck and free Tanya. With Tanya's help, take out the air defenses on the island and a Chinook will arrive to rescue her. Then destroy all remaining Soviet buildings and units.
SideName=Greece

[scg06ea]
CD=-1
Scenario=Maps\Missions\scg06ea.ini
Description=  <none>
LongDescription= Priority One is to establish a base and get your spy into one of the Soviet tech centers in the base across the gulf. Data on the Iron Curtain is in there and we need it. Once you get the data complete your mission... wipe out everything.
SideName=Greece

[scg07ea]
CD=-1
Scenario=Maps\Missions\scg07ea.ini
Description=  Sunken Treasure
LongDescription= LANDCOM 16 HQS.@TOP SECRET.@TO: FIELD COMMANDER A9@@INTERCEPTION OF SOVIET COMMUNIQUE INDICATES THEIR IRON CURTAIN RESEARCH WAS SET BACK BY ESPIONAGE. EXCELLENT WORK, COMMANDER!@@COMMUNIQUE WAS TRACED BACK TO SECRET SOVIET BASE IN BORNHOLM. INVESTIGATE POSSIBLE CONNECTION WITH IRON CURTAIN RESEARCH. CAPTURE RADAR CENTER AND DESTROY SUB PRODUCTION CAPABILITY.@@CONFIRMATION CODE 1138.@@TRANSMISSION ENDS.
SideName=Greece

[scg08ea]
CD=-1
Scenario=Maps\Missions\scg08ea.ini
Description=  <none>
LongDescription= Our latest technology, the Chronosphere, is housed in this research station. The timer represents the appointed time for the completion of a vital experiment. The Soviets have learned of this and are moving in. Protect the Chronosphere and the Advanced-Tech research center. Make sure the base is fully powered at the appointed time. If not, all will be lost!
SideName=Greece

[scg09ea]
CD=-1
Scenario=Maps\Missions\scg09ea.ini
Description=  <none>
LongDescription= One of Stalin's top atomic strategists, Vladimir Kosygin, wishes to defect. His knowledge of Stalin's atomic strategies is invaluable to us. We wish to "extract" him from the Riga compound, where he is stationed. @@Use a spy to infiltrate the Soviet command center and contact Kosygin. Once he is out of the building, get him back to your base any way you  can.
SideName=Greece

[scg10ea]
CD=-1
Scenario=Maps\Missions\scg10ea.ini
Description=  Suspicion
LongDescription= Kosygin has indicated that this is the site of Stalin's main atomic weapons plant. Use extreme care in approaching the Soviet base -- we don't know if any atomic bombs are armed yet. Take the facility off-line and then destroy any atomic weapons that exist.
SideName=Greece

[scg11ea]
CD=-1
Scenario=Maps\Missions\scg11ea.ini
Description=  <none>
LongDescription= Our assault on the USSR is underway, although our efforts are being hindered by large pockets of soviet armor. To counter this we need to move warships up the Volga river, but there is a bottleneck near Volograd which you must clear so our naval vessels can move in. Good Luck.
SideName=Greece

[scg12ea]
CD=-1
Scenario=Maps\Missions\scg12ea.ini
Description=  Takedown
LongDescription= Rumors abound that the Soviet Iron Curtain is nearing completion. In addition, an even more powerful version of that weapon is also in the works. One research facility is more protected than the rest - find out why. Capture all technology centers, and destroy any Iron Curtain prototype that you encounter.@Our newly developed Longbow Helicopter should be able to assist your attacks.
SideName=Greece

[scg13ea]
CD=-1
Scenario=Maps\Missions\scg13ea.ini
Description=  Focused Blast
LongDescription= LANDCOM 16 HQS.@TOP SECRET.@TO: FIELD COMMANDER A9@@CONGRATULATIONS. CAPTURING TECH CENTERS HAS REVEALED AN UNDERGROUND WEAPONS FACILITY. PLACE EXPLOSIVE CHARGES ON ALL GENERATORS. RESULTING EXPLOSIONS SHOULD DESTROY FACILITY.@GET OUT BEFORE NERVE GAS IS USED.@@TRANSMISSION ENDS.
SideName=Greece

[scg14ea]
CD=-1
Scenario=Maps\Missions\scg14ea.ini
Description=  No remorse
LongDescription= This is it -- the final confrontation! The Soviets have nowhere to run now. The only thing that remains is to topple the Soviet seat of power. Destroy everything to make sure that no one takes Stalin's place. No sorrow. No pity. No remorse.
SideName=Greece