[TypeSelect]
UIName=Select Same Type
Category=Selection
Description=Select units that are the type of your currently selected units.
DefaultKey=84

[]
UIName=
Category=Selection
Description=
DefaultKey=80

[]
UIName=
Category=Selection
Description=
DefaultKey=0

[]
UIName=
Category=Selection
Description=
DefaultKey=89

[]
UIName= 
Category=
Description= 
DefaultKey=116

[]
UIName= 
Category=
Description= 
DefaultKey=117

[]
UIName= 
Category=
Description= 
DefaultKey=118

[]
UIName= 
Category=
Description= 
DefaultKey=119

[]
UIName= 
Category=s
Description= 
DefaultKey=120

[]
UIName= 
Category=
Description= 
DefaultKey=121

[]
UIName= 
Category=
Description= 
DefaultKey=122

[]
UIName= 
Category=
Description= 
DefaultKey=123

[]
UIName=
Category=Interface
Description=
DefaultKey=81

[]
UIName=
Category=Interface
Description=
DefaultKey=87

[]
UIName=
Category=Interface
Description=
DefaultKey=69

[]
UIName=
Category=Interface
Description=
DefaultKey=82

[]
UIName=
Category=Interface
Description=
DefaultKey=339

[]
UIName=
Category=Interface
Description=
DefaultKey=75

[]
UIName=
Category=Interface
Description=
DefaultKey=76

[]
UIName=
Category=Interface
Description=
DefaultKey=90

;[TogglePower]
;UIName=Power Mode
;Category=Interface
;Description=Enable power mode (allows powering structures on and off).
;DefaultKey=0

[]
UIName=
Category=Development
Description=
DefaultKey=0

[]
UIName=
Category=Development
Description=
DefaultKey=0

[]
UIName=
Category=Development
Description=
DefaultKey=0

[]
UIName=
Category=Development
Description=
DefaultKey=0

[]
UIName=
Category=Development
Description=
DefaultKey=0

[]
UIName=
Category=Selection
Description=
DefaultKey=78

[]
UIName=
Category=Selection
Description=
DefaultKey=77

[]
UIName=
Category=Interface
Description=
DefaultKey=12

[]
UIName=
Category=Interface
Description=
DefaultKey=27

[]
UIName=
Category=Interface
Description=
DefaultKey=72

[]
UIName=
Category=Interface
Description=
DefaultKey=70

[]
UIName=
Category=Interface
Description=
DefaultKey=112

[]
UIName=
Category=Interface
Description=

[]
UIName=
Category=Interface
Description=
DefaultKey=114

[]
UIName=
Category=Interface
Description=
DefaultKey=115

[]
UIName=
Category=Interface
Description=
DefaultKey=624

[]
UIName=
Category=Interface
Description=
DefaultKey=625

[]
UIName=
Category=Interface
Description=
DefaultKey=626

[]
UIName=
Category=Interface
Description=
DefaultKey=627

[]
UIName=
Category=Interface
Description=
DefaultKey=66

[]
UIName=
Category=Interface
Description=
DefaultKey=110

[]
UIName=
Category=Interface
Description=
DefaultKey=32

[]
UIName=
Category=Control
Description=
DefaultKey=65

[DeployObject]
UIName=Deploy Object
Category=Control
Description=Deploy selected units.
DefaultKey=68

[GuardObject]
UIName=Guard
Category=Control
Description=Make your selected units guard the nearby area and automatically attack enemies.
DefaultKey=71

[ScatterObject]
UIName=Scatter
Category=Control
Description=Make your selected units scatter.
DefaultKey=88

[StopObject]
UIName=Stop Object
Category=Control
Description=Stop your selected units.
DefaultKey=83

[AllToCheer]
UIName=Cheer
Category=Control
Description=Make all of your infantry units cheer.
DefaultKey=67

