[INISystem]
BasedOn=GenericWindow.ini

[OptionsWindow]

[lblDetailLevel]
ToolTip=Select the level of detail. Lower levels will reduce visual effects and increase performance.
Enabled=False
Visible=False

[ddDetailLevel]
ToolTip=Select the level of detail. Lower levels will reduce visual effects and increase performance.
Enabled=False
Visible=False

[lblRenderer]
ToolTip=Select the DDraw wrapper to use. If you experience graphical or performance issues, try a different wrapper.

[ddRenderer]
ToolTip=Select the DDraw wrapper to use. If you experience graphical or performance issues, try a different wrapper.

[chkBackBufferInVRAM]
Text=Back Buffer in Video Memory
ToolTip=Enable back buffer in VRAM. Reduces performance, but is necessary on some systems.
Enabled=False
Visible=False

; ==========================
; Updater Menu Items
; ==========================

[UpdaterOptionsPanelExtraControls]
0=lblUpdateChannel:XNALabel
1=ddUpdateChannel:FileSettingDropDown
2=lblUpdateChannelDescription:XNALabel
3=btnCncnetSupport:XNALinkButton

[lblUpdateChannel]
Location=12,240
Size=90,24
Text=Update Channel:

[btnForceUpdate]
Location=407,213
Size=133,23

[ddUpdateChannel]
Location=115,238
Size=280,21
Items=Developer Testing (NOT FINAL)
DefaultValue=0
CheckFilePresence=yes
ResetUnselectableItem=yes
ForceApplyUnselectableItem=no
RestartRequired=true
Item0File0=Resources/UpdaterConfig_Dev.ini,Resources/UpdaterConfig.ini,OverwriteOnMismatch
ToolTip=Switch between update Channels. Requires client restart.
Enabled=true

[lblUpdateChannelDescription]
Location=12,264
Text=**WARNING**:@Using the Beta or Dev channel may bring unexpected errors or behavior.@It is meant to allow public testing of upcom