;
; tutorial.ini file for Flame Dancers:Genesis
; to be used for the first mission set
;
;
[Tutorial]
1=Objective 1 Complete
2=Objective 2 Complete
3=Objective 3 Complete
4=Defend Command Center
5=Destroy all Allied units and structures
6=Destroy all Soviet units and structures
7=Build your base

;Specific text
;MAX is below! Don't exceed!
;X=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

8=Capture and defend War Factory
9=Capture the Ship Yard
10=Free Brother Harkins
11=Get spy into Bio-Research Laboratory
12=Patrol routes are now visible
13=Biological weapon stolen
14=Engineer reinforcements have arrived
15=From Renee: Curse you!
16=From Dominic: Remorse's fanaticism will
17=kill us all! Think you fool!
18=From civilians: Leave us alone.
19=Prime Minister's plane has arrived
20=You failed to shoot down the plane
21=Water supply poisoned
22=Water processor destroyed
23=Destroy hospitals and hospital staff
24=Get spies into water processing plants
25=Abandonded repair bay revealed
26=Get volunteer into weapons factory
27=From driver: Remember my sacrifice!
28=The Secretary-General has arrived
29=Sniper is waiting for Secretary-General
30=to arrive to minimise chance of detection
31=Warning: EDF troops are attempting to
32=destroy the bridges!
33=Research building destroyed
34=Destroy defensive structures and tents.
35=Kill the General.
36=Testing period has commenced
37=Testing period has been completed
38=Destroy the 3 prototype vehicles
39=Destroy the northern village and kill the
40=Finance Minister
41=From Josua: See you in Zurich
42=Josua needs to use the police station
43=Finance Minister imposter is on his way
44=Only destroy the northern village
45=The riot squad has been called
46=The Finance Minister has been killed
47=Josua was killed!
48=Prototype destroyed
49=Destroy the two prototype research
50=facilities and any prototypes
51=Brother Harkins was killed
52=Engineers will now secure airfields
53=Convoy truck will arrive in four minutes
54=Convoy truck has been sighted
55=Convoy truck has escaped
56=All Engineers killed
57=Planes will return in one hour
58=Planes have returned from Romania
59=Abdul was killed
60=Mikal was killed
61=The generals' replacements have arrived
62=Destroy all Turkish forces
63=Get the spies into the two radar domes
64=Destroy all chronospheres
65=Location of the chronospheres revealed

;all civilians destroyed

66=Good, all the less for the Day of Flame
67=Congratulations for completing the first
68=campaign. The second awaits you.
69=<added so Counterstrike won't crash>
70=<added so Counterstrike won't crash>
71=<added so Counterstrike won't crash>
72=<added so Counterstrike won't crash>
73=<added so Counterstrike won't crash>
74=<added so Counterstrike won't crash>
75=<added so Counterstrike won't crash>
76=<added so Counterstrike won't crash>
77=<added so Counterstrike won't crash>
78=<added so Counterstrike won't crash>
79=<added so Counterstrike won't crash>
80=<added so Counterstrike won't crash>
81=<added so Counterstrike won't crash>
82=<added so Counterstrike won't crash>
83=<added so Counterstrike won't crash>
84=<added so Counterstrike won't crash>
85=<added so Counterstrike won't crash>
86=<added so Counterstrike won't crash>
87=<added so Counterstrike won't crash>
88=<added so Counterstrike won't crash>
89=<added so Counterstrike won't crash>
90=<added so Counterstrike won't crash>
91=<added so Counterstrike won't crash>
92=<added so Counterstrike won't crash>
93=<added so Counterstrike won't crash>
94=<added so Counterstrike won't crash>
95=<added so Counterstrike won't crash>
96=<added so Counterstrike won't crash>
97=<added so Counterstrike won't crash>
98=<added so Counterstrike won't crash>
99=<added so Counterstrike won't crash>
100=<added so Counterstrike won't crash>
101=<added so Counterstrike won't crash>
102=<added so Counterstrike won't crash>
